config/routes.rb
Rails.application.routes.draw do
  resources :chores
  get '/board', to: "board#index"
  get '/board2', to: "board#other"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chore.rb
# frozen_string_literal: true

class Chore < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/board_controller.rb
# frozen_string_literal: true

class BoardController < ApplicationController
  def index
    # flash.now[:success] = {
    #   title: "Successfully Sign Up",
    #   body: "Welcome to our application"
    # }
    # flash.now[:alert] = {
    #   title: "Some alert",
    #   body: "something got wrong!"
    # }
    # flash.now[:error] = {
    #   title: "Some error",
    #   body: "something got wrong!"
    # }
    # flash.now[:notice] = {
    #   title: "Some notice",
    #   body: "something to inform"
    # }
  end

  def other; end
end

app/controllers/chores_controller.rb
# frozen_string_literal: true

class ChoresController < ApplicationController
  before_action :set_chore, only: %i[ show edit update destroy ]
  after_action :broadcast_insert, only: %i[create]
  after_action :broadcast_remove, only: %i[destroy]

  # GET /chores or /chores.json
  def index
    @chores = Chore.all
  end

  # GET /chores/1 or /chores/1.json
  def show
  end

  # GET /chores/new
  def new
    @chore = Chore.new
  end

  # GET /chores/1/edit
  def edit
  end

  # POST /chores or /chores.json
  def create
    @chore = Chore.new(chore_params)

    respond_to do |format|
      if @chore.save
        format.html { redirect_to @chore, notice: "Chore was successfully created." }
        format.json { render :show, status: :created, location: @chore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chores/1 or /chores/1.json
  def update
    respond_to do |format|
      if @chore.update(chore_params)
        format.html { redirect_to @chore, notice: "Chore was successfully updated." }
        format.json { render :show, status: :ok, location: @chore }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1 or /chores/1.json
  def destroy
    @chore.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: "" }
      format.html { redirect_to chores_url, notice: "Chore was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chore
      @chore = Chore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chore_params
      params.require(:chore).permit(:title, :content)
    end

    def broadcast_insert
      return if @chore.errors.any?
      Turbo::StreamsChannel.broadcast_append_to(
        "chores",
        target: "chores",
        partial: "chores/chore",
        locals: { chore: @chore }
      )
    end

    def broadcast_update
      return if @chore.errors.any?
      Turbo::StreamsChannel.broadcast_replace_to(
        "chores",
        target: ActionView::RecordIdentifier.dom_id(@chore),
        partial: "chores/chore",
        locals: { chore: self }
      )
    end

    def broadcast_remove
      return unless @chore.destroyed?
      Turbo::StreamsChannel.broadcast_remove_to(
        "chores",
        target: ActionView::RecordIdentifier.dom_id(@chore)
      )
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/board/_card_preview.html.erb
<li class="mt-3">
  <a href="#" class="block p-5 bg-white shadow rounded-md">
    <div class="flex justify-between mb-1">
      <p class="text-sm font-medium leading-snug text-gray-900 mr-0.5">
      <%= title %>
      </p>
      <span class="flex-shrink-0">
        <img class="w-6 h-6 rounded-full"
             src=<%= img_url %>
             alt=""
        />
      </span>
    </div>
    <div class="flex items-baseline justify-between">
      <time datetime=<%= date.strftime("%Y-%m-%d") %> class="text-sm text-gray-600"><%= date.strftime("%b %d") %></time>
      <div>
        <span class="inline-flex items-center px-2 py-1 leading-tight bg-<%= tag_color %>-100 rounded">
          <svg class="w-2 h-2 text-<%= tag_color %>-500" viewBox="0 0 8 8" fill="currentColor">
            <circle cx="4" cy="4" r="3" />
          </svg>
          <span class="ml-2 text-sm font-medium text-<%= tag_color %>-700"><%= tag_text %></span>
        </span>
      </div>
    </div>
  </a>
</li>

app/views/board/_modal_example.html.erb
<!-- Source: https://www.section.io/engineering-education/creating-a-modal-dialog-with-tailwind-css/-->

<!-- modal's parent div that overlay background page. Dynamically remove 'hidden' class to show up -->
<div class="fixed inset-0 hidden w-full h-full overflow-y-auto bg-gray-800 bg-opacity-50"
     id="my-modal"
>
  <!-- modal content exemple -->
  <div class="relative p-5 mx-auto bg-white border shadow-lg top-20 w-96 rounded-md">
    <div class="mt-3 text-center">
      <div class="flex items-center justify-center w-12 h-12 mx-auto bg-green-100 rounded-full">
        <svg
          class="w-6 h-6 text-green-600"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M5 13l4 4L19 7"
          ></path>
        </svg>
      </div>
      <h3 class="text-lg font-medium text-gray-900 leading-6">Successful!</h3>
      <div class="py-3 mt-2 px-7">
        <p class="text-sm text-gray-500">
          Account has been successfully registered!
        </p>
      </div>
      <div class="items-center px-4 py-3">
        <button
          id="ok-btn"
          class="w-full px-4 py-2 text-base font-medium text-white bg-green-500 rounded-md shadow-sm hover:bg-green-600 focus:outline-none focus:ring-2 focus:ring-green-300"
        >
          OK
        </button>
      </div>
    </div>
  </div>
</div>

app/views/board/_other_card_preview.html.erb
<li class="mt-3">
  <a href="#" class="block p-5 bg-white shadow-lg rounded-md transform hover:scale-110">
    <div class="flex justify-between mb-2">
      <p class="text-sm font-medium leading-snug text-gray-900 mr-0.5">
      <%= title %>
      </p>
      <span class="flex-shrink-0">
        <img class="w-6 h-6 rounded-full"
             src=<%= img_url %>
             alt=""
        />
      </span>
    </div>
    <div class="flex items-baseline justify-between">
      <time datetime=<%= date.strftime("%Y-%m-%d") %> class="text-sm text-wood-700"><%= date.strftime("%b %d") %></time>
        <span class="inline-flex items-center px-2 py-1 leading-tight bg-<%= tag_color %>-100 rounded">
          <span class="text-sm font-medium text-<%= tag_color %>-700"><%= tag_text %></span>
        </span>
    </div>
  </a>
</li>

app/views/chores/_chore.html.erb
<div
  id="<%= dom_id chore %>"
  class="p-3 my-3 bg-white shadow-lg group transition duration-700 ease-in-out transform hover:scale-125 hover:z-10 rounded-md"
>
  <div class="flex flex-col">
    <div class="flex justify-between">
      <p class="text-lg font-bold leading-snug text-gray-900 mr-0.5">
        <%= chore.title %>
      </p>
      <time
        datetime=<%= chore.created_at.strftime("%Y-%m-%d") %>
        class="invisible text-sm text-indigo-700 group-hover:visible"
      >
        <%= chore.created_at.strftime("%b %d") %>
      </time>
    </div>
    <a href="#">
      <p class="leading-snug text-gray-900">
        <%= chore.content %>
      </p>
    </a>
    <div class="flex justify-end space-x-2">
      <%= button_to edit_chore_path(chore), method: :get, data: { turbo_frame: 'modal' }, class:"invisible w-5 h-5 text-indigo-500 cursor-pointer group-hover:visible hover:text-black transition-all duration-600 ease-in-out" do %>
        <svg stroke="currentColor" fill="none" stroke-width="1.7" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round">
          <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/>
          <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>
        </svg>
      <% end %>
      <%= button_to chore_path(chore), method: :delete, class: "invisible w-5 h-5 text-indigo-500 cursor-pointer group-hover:visible hover:text-black transition-all duration-600 ease-in-out" do %>
        <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16">
          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path><path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
        </svg>
      <% end %>
    </div>
  </div>
</div>

app/views/chores/_form.html.erb
<%= form_with(model: chore, id:"chore_form", class: "grow flex flex-col") do |form| %>
  <% if chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
        <% chore.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="items-center">
    <div class="flex flex-col w-5/6 mx-auto">
      <%= form.text_field :title, placeholder: "Title", class: "p-3 mt-2 leading-none text-gray-900 bg-gray-100 border border-gray-200 rounded" %>
    </div>
  </div>

  <div class="grow flex flex-col w-5/6 mx-auto">
    <%= form.text_area :content, placeholder: "Content", class: "grow h-40 p-3 mt-2 text-base leading-none text-gray-900 bg-gray-100 border border-gray-200 rounded" %>
  </div>

  <div class="flex items-center justify-center w-full">
    <%= form.submit class: "px-10 py-4 my-2 font-semibold leading-none text-white rounded bg-slate-700 hover:bg-slate-900" %>
  </div>
<% end %>

app/views/chores/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@chore) %>

app/views/chores/edit.html.erb
<%= render ChoreModalComponent.new(title: "Editing Chore") do %>
  <%= render "form", chore: @chore %>
<% end %>

app/views/chores/new.html.erb
<%= render ChoreModalComponent.new(title: "New Chore") do %>
  <%= render "form", chore: @chore %>
<% end %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @chore %>

<div>
  <%= link_to "Edit this chore", edit_chore_path(@chore) %> |
  <%= link_to "Back to chores", chores_path %>

  <%= button_to "Destroy this chore", chore_path(@chore), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningHotwire</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= turbo_frame_tag "modal" %>
    <%= yield %>
  </body>
</html>